services:
  data-scenario-center-ide:
    build:
      context: ./data-scenario-center-ide
      dockerfile: browser.Dockerfile
    container_name: data-scenario-center-ide
    ports:
      - 3000:3000

  data-scenario-center-backend:
    build:
      context: ./data-scenario-center-backend
      dockerfile: Dockerfile
    container_name: data-scenario-center-backend
    volumes:
      - conda_volume:/opt/conda/envs
    ports:
      - 8000:8000

  data-scenario-center-front-react:
    build:
      context: ./data-scenario-center-front-react
      dockerfile: Dockerfile
    ports:
      - "3001:80"

volumes:
  conda_volume:
