services:
  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: dscr_grafana
    ports:
      - "53000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - dscr_grafana_data:/var/lib/grafana

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: dscr_mariadb
    ports:
      - "53306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dscr_rootpassword
      - MYSQL_DATABASE=dscr_db
      - MYSQL_USER=dscr_user
      - MYSQL_PASSWORD=dscr_password
    volumes:
      - dscr_mariadb_data:/var/lib/mysql

  # PostgreSQL Service
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: dscr_db
      POSTGRES_USER: dscr_user
      POSTGRES_PASSWORD: dscr_password
    volumes:
      - dscr_postgresql_data:/var/lib/postgresql/data

  # Valkey Service
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    command: valkey-server --save 60 1 --loglevel warning
    ports:
      - "58080:8080" # replace with Valkey service port if needed
    volumes:
      - dscr_valkey_data:/data
    environment:
      - VALKEY_DB_USER=dscr_user
      - VALKEY_DB_PASSWORD=dscr_password

  # Apache Cassandra Service
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "59042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=dscr_cluster
      - CASSANDRA_SEEDS=cassandra
    volumes:
      - dscr_cassandra_data:/var/lib/cassandra

  jobmanager:
    image: flink:latest
    ports:
      - "58081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

volumes:
  dscr_grafana_data:
  dscr_mariadb_data:
  dscr_postgresql_data:
  dscr_cassandra_data:
  dscr_valkey_data: